-- return {
-- 	"geg2102/nvim-python-repl",
-- 	event = "VeryLazy",
-- 	dependencies = "nvim-treesitter",
-- 	ft = { "python" },
-- 	config = function()
-- 		require("nvim-python-repl").setup({
-- 			execute_on_send = false,
-- 			vsplit = false,
-- 			--			spawn_command = "python3",
-- 		})
-- 		vim.keymap.set("n", "<leader>rp", function()
-- 			require("nvim-python-repl").send_current_cell_to_repl()
-- 		end, { desc = "Sends the cell under cursor to repl" })
-- 	end,
-- }
